### ISSUE TITLE
Use a resizing tool?

### ISSUE THREAD

**Issue by wmertens** [ethanmad/chromeos-resize#4]
I wonder why you destroy the partitions instead of resizing them. IIRC GNU PartEd can do it.

(I'm researching if a ChromeBook would be ok for a dev environment, and it would be imperative to have a data partition that ChromeOS doesn't mess with and that would preferably show up in Crostini)

**Comment by ethanmad** [comment]
Hello, unless I am remembering incorrectly and misunderstanding the code, this does resize partitions rather than delete them. This occurs in the section beginning at [line 173](https://github.com/ethanmad/chromeos-resize/blob/5bde8f8287747d448ac9c05807350ccd40a6fb56/cros-resize.sh#L173) using `cgpt add` to modify the partition layout. (I might be misinterpreting this; it's been a few years.) Data loss is inevitable due to the ChromeOS partition layout. kern c and rootfs c come before the user state partition, so the resize will destroy data in the user state partition.

I don't believe ChromeOS ships with `parted`, but if you had access to parted you could just as easily use that to resize your partition layout. This script was originally built for dual-booting, in which case ChromeOS was mainly kept around for firmware updates. Thus, installing anything not shipped with ChromeOS seemed overkill.

I haven't used Crostini. I'd guess that you could mount and access rootfs C in Crostini, but I'm not sure. I don't see why it would be any other storage device, though.

As for whether a Chromebook would be ok for a dev environment, it depends on the device. Dual-booting is easy if the drivers are mainlined (if not, and you are ok with Ubuntu, look at GalliumOS). Crostini seems nice if you need frequent access to ChromeOS or Android apps.

**Comment by wmertens** [comment]
Thank you for your insights! I suppose I can close this then :)

**Comment by ethanmad** [comment]
For completeness's sake, I did some research and found a larger project which has more specific use-cases, https://chrx.org/. That suite might be useful for you if you are interested in dual-booting one of their supported OSes, and their partition resizing script is very similar. I'm glad to be able to help!
